---
apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorApp"
metadata:
  name: "webapp-kubedir"
spec:
  app: "webapp"
  systemdRequired: true
  defaultPersistDirs:
  - "/usr/src/app/data"
  defaultEventList:
  - configure
  - addnodes
  - delnodes
  config:
    roleServices:
    - serviceIDs:
      - http
      roleID: webapp-kubedir
    selectedRoles:
    - webapp-kubedir
  label:
    name: webapp-kubedir
    description: WebApp Statefull Appliction example  
  defaultImageRepoTag: docker.io/stefds/webapp:latest
  defaultConfigPackage: 
  distroID: stefds/webapp
  version: 'latest'
  configSchemaVersion: 7
  services:
  - endpoint:
      port: 8090
      isDashboard: true
    id: http
    label:
      name: HTTP
  roles:
  - cardinality: 1+
    id: webapp-kubedir
