apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels: 
    hpecp.hpe.com/hpecp-internal-gateway: "true"
spec:
  selector:
    run: webapp
  ports:
  - name: webapp
    protocol: TCP
    port: 8088
    targetPort: 3000
  type: NodePort
