--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      run: webapp
  template:
    metadata:
      labels:
        run: webapp
    spec: 
      containers:
        - name: webapp
          image: stefds/webapp
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels: 
    hpecp.hpe.com/hpecp-internal-gateway: "true"
spec:
  selector:
    run: webapp
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
